version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - app-data:/app/data

  db:
    build:
      context: .
      dockerfile: docker/db.dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  app-data:
